[project]
name = "algogators-application"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "statsmodels>=0.14.6",
    "yfinance>=1.0",
]
